In [1]:
import numpy as np

In [3]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672]) # 대한민국의 인당 gdp 데이터

데이터 사이언스에서는 인덱스 위치를 아는 상태에서 값을 받아올 때도 있지만, 위치를 기반하여 가져오는게 아닌,\
**특정 조건을 충족하는 값**을 받아오고 싶을 때가 있음. numpy에서 이것을 쉽게 할 수 있게 해줌

위 gdp_array에서 **10000이 넘는 값**들만 가져와보자.

In [4]:
gdp_array > 10000 # gdp_array를 10000이랑 비교하는 코드

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

gdp_array의 **각 값을 10000이랑 비교**해서\
**해당 조건이 만족되면 True**를 **아니면 False로 값이 정해짐.**

In [7]:
mask = gdp_array > 10000 # mask라는 변수에 해당 조건을 저장함
gdp_array[mask]          # gdp_array인덱스에 mask를 넣음 (= gdp_array[gdp_array > 10000])

array([10385, 12565, 13403, 12398, 10672])

위와 같이 **10000이 넘는 값(조건 만족 : True) 만 받아오게 됨.**\
이 방법을 앞으로 자주 사용하게 되는데 이것을 **불린 인덱싱** or **masking** 이라고 함

위 방법을 활용하여 *10000보다 크거나 8000보다 작은 값*을 가져오는 코드 작성

In [14]:
gdp_array > 10000

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [18]:
gdp_array < 8000

array([ True,  True, False, False, False, False, False, False, False,
       False])

위 조건을 만족하려면, **각 인덱스마다 하나라도 True 가 있을 때 결과는 True여야 한다.** 파이썬의 'or' 처럼

In [17]:
mask2 = (gdp_array > 10000) | (gdp_array < 8000)   # gdp_array 내 값이 10000보다 크거나, 8000보다 작다는 조건
gdp_array[mask2]

array([ 6610,  7637, 10385, 12565, 13403, 12398, 10672])

**|** == **or** 과 같은 역할을 한다.\
**|** 사용 시 **() | () 괄호를 꼭 둘러줘야 동작한다.** 

반대로 8000과 10000 사이의 있는 값들을 받아오고 싶을 땐 \
**파이썬 and 연산자 같은 걸 사용하면 된다.**

In [19]:
gdp_array[(gdp_array <= 10000) & (gdp_array >= 8000)]  

array([8127, 8885, 8282])

위와 같이 &를 사용하여, and 기법을 사용한다.\
이것도 마찬가지고 **() & ()** 로 사용한다.